### ISSUE TITLE
Session saved with external monitor can't be restored on single display

### ISSUE THREAD

**Issue by loxosceles** [johannesjo/gnome-shell-extension-window-session-manager#13]
Saved a session with two displays (laptop and external). Later tried to restore with single display (laptop), but got this error message. (This shows up after trying it again from the console).

```
no data for current display id '1920x1080' saved yet
An error occurred TypeError: Cannot read property 'forEach' of undefined
    at startSessionPrograms (/home/myuser/.nvm/versions/node/v10.9.0/lib/node_modules/linux-window-session-manager/lib/index.js:414:14)
    at closeAllWindowsIfSet.then.then.then.then (/home/myuser/.nvm/versions/node/v10.9.0/lib/node_modules/linux-window-session-manager/lib/index.js:214:18)
Generic Error in Main Handler TypeError: Cannot read property 'forEach' of undefined
    at startSessionPrograms (/home/myuser/.nvm/versions/node/v10.9.0/lib/node_modules/linux-window-session-manager/lib/index.js:414:14)
    at closeAllWindowsIfSet.then.then.then.then (/home/myuser/.nvm/versions/node/v10.9.0/lib/node_modules/linux-window-session-manager/lib/index.js:214:18) TypeError: Cannot read property 'forEach' of undefined
    at startSessionPrograms (/home/myuser/.nvm/versions/node/v10.9.0/lib/node_modules/linux-window-session-manager/lib/index.js:414:14)
    at closeAllWindowsIfSet.then.then.then.then (/home/myuser/.nvm/versions/node/v10.9.0/lib/node_modules/linux-window-session-manager/lib/index.js:214:18)
(node:19242) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'forEach' of undefined
    at startSessionPrograms (/home/myuser/.nvm/versions/node/v10.9.0/lib/node_modules/linux-window-session-manager/lib/index.js:414:14)
    at closeAllWindowsIfSet.then.then.then.then (/home/myuser/.nvm/versions/node/v10.9.0/lib/node_modules/linux-window-session-manager/lib/index.js:214:18)
(node:19242) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19242) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

When I plug in my external monitor, it opens my saved session (although not entirely error free).

**Comment by johannesjo** [comment]
Hey there! you need to execute `lwsm save sessionName` for every display combination as they're stored separately.

**Comment by loxosceles** [comment]
Ok, I see it's working for the same display setup. Still, I think it would be better to catch this error. Or, somehow link display information to the session. It's kind of confusing if you have a bunch of saved session and you don't know if they will work with your current display setup.
 Btw, awesome extension! I hope you keep improving it!

**Comment by johannesjo** [comment]
I agree. Hard to make guesses where to put the application Windows though. Maybe for those cases it makes sense just to open the apps without positioning them and display an info of some sort. I'll think about it. Let me know if you have any suggestions.
