### ISSUE TITLE
Applet fails to execute lwsm to save or restore sessions.

### ISSUE THREAD

**Issue by wlpeters** [johannesjo/gnome-shell-extension-window-session-manager#15]
lwsm command works fine and the applet is installed. When clicked, the applet displays a message displaying the lwsm command. But nothing more happens.  It is as if the lwsm command failed. When I save new sessions with lswm, the applet sees the new names. So it knows where to look for them, but won't write new ones or restore any sessions.

**Comment by johannesjo** [comment]
Hey there! Thanks for reporting. It's weird that there is no error message. A likely error case however is that the extension is not able to execute the module. Maybe lwsm is available from the command line, but not for the extension. You could try adding your node binaries to `~/.profile`.

**Comment by johannesjo** [comment]
@wlpeters Do you have node installed for all users or just for the current user? In my case (using nvm) the following helped: 
```
sudo ln -s /home/jojojojo/.nvm/versions/node/v10.15.0/bin/node /usr/bin/node
```

**Comment by superg28** [comment]
Having a similar issue on Pop!_OS 19.04, node 10.16.3. Getting the following error

`{ Error: Bad atom
    at ReadFixedRequest.callback (/home/superg28/.nvm/versions/node/v10.16.3/lib/node_modules/linux-window-session-manager/node_modules/x11/lib/xcore.js:465:29)
    at ReadFixedRequest.execute (/home/superg28/.nvm/versions/node/v10.16.3/lib/node_modules/linux-window-session-manager/node_modules/x11/lib/unpackstream.js:41:10)
    at UnpackStream.resume (/home/superg28/.nvm/versions/node/v10.16.3/lib/node_modules/linux-window-session-manager/node_modules/x11/lib/unpackstream.js:165:30)
    at UnpackStream.write (/home/superg28/.nvm/versions/node/v10.16.3/lib/node_modules/linux-window-session-manager/node_modules/x11/lib/unpackstream.js:102:10)
    at Socket.<anonymous> (/home/superg28/.nvm/versions/node/v10.16.3/lib/node_modules/linux-window-session-manager/node_modules/x11/lib/xcore.js:88:21)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  error: 5,
  seq: 4,
  message: 'Bad atom',
  badParam: 0,
  minorOpcode: 0,
  majorOpcode: 17 }
(node:10096) UnhandledPromiseRejectionWarning: Error: Bad atom
    at ReadFixedRequest.callback (/home/superg28/.nvm/versions/node/v10.16.3/lib/node_modules/linux-window-session-manager/node_modules/x11/lib/xcore.js:465:29)
    at ReadFixedRequest.execute (/home/superg28/.nvm/versions/node/v10.16.3/lib/node_modules/linux-window-session-manager/node_modules/x11/lib/unpackstream.js:41:10)
    at UnpackStream.resume (/home/superg28/.nvm/versions/node/v10.16.3/lib/node_modules/linux-window-session-manager/node_modules/x11/lib/unpackstream.js:165:30)
    at UnpackStream.write (/home/superg28/.nvm/versions/node/v10.16.3/lib/node_modules/linux-window-session-manager/node_modules/x11/lib/unpackstream.js:102:10)
    at Socket.<anonymous> (/home/superg28/.nvm/versions/node/v10.16.3/lib/node_modules/linux-window-session-manager/node_modules/x11/lib/xcore.js:88:21)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at Pipe.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
(node:10096) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10096) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by johannesjo** [comment]
@superg28 this is related: https://github.com/johannesjo/linux-window-session-manager/issues/47

You can use version v2.1.31 in the meantime.

**Comment by InsonusK** [comment]
I have got same problem. I have found solution/reason: if terminal is opened everything is fine, when i close it extension stop working. 

Linux Ubuntu 19.10
