### ISSUE TITLE
unknown error when spawn okular

### ISSUE THREAD

**Issue by schrodog** [johannesjo/gnome-shell-extension-window-session-manager#16]
When I type `lwsm restore`, all windows except okular restored,

```
Status: "nautilus.Nautilus" is running: true 1 0
Status: "okular.okular" is running: false 1 0
Starting: okular.desktop
Status: "Navigator.Firefox" is running: true 1 0
Status: "gnome-terminal-server.Gnome-terminal" is running: true 1 0
Wait for all applications to start
events.js:173
      throw er; // Unhandled 'error' event
      ^

Error: spawn okular.desktop ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:421:16)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:252:12)
    at onErrorNT (internal/child_process.js:421:16)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
```

**Comment by johannesjo** [comment]
Have a look here: https://github.com/johannesjo/linux-window-session-manager#troubleshooting--issues
