### ISSUE TITLE
Pop!_OS 20.04 issues in saving session.

### ISSUE THREAD

**Issue by ngeraks** [johannesjo/gnome-shell-extension-window-session-manager#33]
Trying to save the session with the gui hangs.
Trying to save it by caling lwsm save asdf results in:
```
lwsm 4.0.5 --> save Thu Aug 19 2021 16:23:34 GMT+0300 (Moscow Standard Time)
ERR: findDesktopFile() cant find file "Viber.desktop"! Searched desktopFileLocations: [ '{home}/.local/share/applications',
  '{home}/.gnome/apps',
  '/usr/share/applications',
  '/usr/local/share/applications',
  '/usr/share/app-install',
  '{home}/.config/autostart',
  '/var/lib/snapd/desktop/applications',
  '/var/lib/flatpak/app',
  '/var/lib/flatpak/exports/share/applications',
  '{home}/.local/share/flatpak/exports/share/applications',
  '/snap/bin',
  '{home}/.local/share/applications',
  '{home}/.gnome/apps',
  '/usr/share/applications',
  '/usr/local/share/applications',
  '/usr/share/app-install',
  '{home}/.config/autostart',
  '/var/lib/snapd/desktop/applications',
  '/var/lib/flatpak/app',
  '/var/lib/flatpak/exports/share/applications',
  '{home}/.local/share/flatpak/exports/share/applications',
  '/snap/bin' ]

 Trying alternative guessing approach for "Gnome-terminal".....
ERR: findDesktopFile() cant find file "gedit.desktop"! Searched desktopFileLocations: [ '{home}/.local/share/applications',
  '{home}/.gnome/apps',
  '/usr/share/applications',
  '/usr/local/share/applications',
  '/usr/share/app-install',
  '{home}/.config/autostart',
  '/var/lib/snapd/desktop/applications',
  '/var/lib/flatpak/app',
  '/var/lib/flatpak/exports/share/applications',
  '{home}/.local/share/flatpak/exports/share/applications',
  '/snap/bin',
  '{home}/.local/share/applications',
  '{home}/.gnome/apps',
  '/usr/share/applications',
  '/usr/local/share/applications',
  '/usr/share/app-install',
  '{home}/.config/autostart',
  '/var/lib/snapd/desktop/applications',
  '/var/lib/flatpak/app',
  '/var/lib/flatpak/exports/share/applications',
  '{home}/.local/share/flatpak/exports/share/applications',
  '/snap/bin' ]

 Trying alternative guessing approach for "gnome".....

 Trying alternative guessing approach for "gnome".....

 Trying alternative guessing approach for "Gnome-terminal".....
Generic Error in Meta Wrapper ERR: findDesktopFile() cant find file "Viber.desktop"! Searched desktopFileLocations: undefined
Generic Error in Meta Wrapper ERR: findDesktopFile() cant find file "gedit.desktop"! Searched desktopFileLocations: undefined

 Trying alternative guessing approach for "ViberPC".....

 Trying alternative guessing approach for "Gedit".....
ERR _guessFilePath() null
Generic Error in Main Handler TypeError: Cannot read property 'stack' of null
    at _catchGenericErr$1 (/usr/local/lib/node_modules/linux-window-session-manager/dist/index.js:1084:61)
    at process._tickCallback (internal/process/next_tick.js:68:7) TypeError: Cannot read property 'stack' of null
    at _catchGenericErr$1 (/usr/local/lib/node_modules/linux-window-session-manager/dist/index.js:1084:61)
    at process._tickCallback (internal/process/next_tick.js:68:7)
saveSession(): An error occurred TypeError: Cannot read property 'stack' of null
    at _catchGenericErr$1 (/usr/local/lib/node_modules/linux-window-session-manager/dist/index.js:1084:61)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:277481) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'stack' of null
    at _catchGenericErr$1 (/usr/local/lib/node_modules/linux-window-session-manager/dist/index.js:1084:61)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:277481) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:277481) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

 Alternative guessing approach for "Gnome-terminal" SUCCESS -> /usr/libexec/gnome-terminal-server

 Alternative guessing approach for "gnome" SUCCESS -> /usr/bin/nautilus

 Alternative guessing approach for "gnome" SUCCESS -> /usr/bin/nautilus

 Alternative guessing approach for "Gnome-terminal" SUCCESS -> /usr/libexec/gnome-terminal-server

 Alternative guessing approach for "Gedit" SUCCESS -> /usr/bin/gedit
 ```
 After these messages the program does not finish.

**Comment by johannesjo** [comment]
Thanks for reporting! Did you try the suggestions from the troubleshooting section:
https://github.com/johannesjo/linux-window-session-manager#troubleshooting--issues
?

**Comment by ngeraks** [comment]
Oh, I had not noticed that! Please excuse me!
Anyway, it seems Viber on my machine is installed with flatpak and the desktop-file is named
~/.local/share/flatpak/exports/share/applications/com.viber.Viber.desktop
Adding "Viber.desktop" to the WM_CLASS_EXCLUSIONS saves the session.

**Comment by johannesjo** [comment]
No worries! I am glad to hear that it works now! Thanks for reporting back!
