### ISSUE TITLE
lwsm fails with "command failed: locate <name>.desktop"

### ISSUE THREAD

**Issue by harshhpareek** [johannesjo/gnome-shell-extension-window-session-manager#4]
I installed lwsm with the following command

```
☁  ~  npm install -g linux-window-session-manager
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
/home/linuxbrew/.linuxbrew/bin/lwsm -> /home/linuxbrew/.linuxbrew/lib/node_modules/linux-window-session-manager/cmd.js
+ linux-window-session-manager@2.1.12
updated 1 package in 4.594s

```
But the gnome extensions page shows a red "Error" and the settings asks for the path to lwsm, which I provided as /home/linuxbrew/.linuxbrew/bin/lwsm. Running the binary directly gives the following error

```
☁   /home/linuxbrew/.linuxbrew/bin/lwsm save                
locate *chrome-endpbjjpgkojalfkdmdhmhpgpipbofgd*.desktop { Error: Command failed: locate *chrome-endpbjjpgkojalfkdmdhmhpgpipbofgd*.desktop

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'locate *chrome-endpbjjpgkojalfkdmdhmhpgpipbofgd*.desktop' }
otherCmd: Generic Error { Error: Command failed: locate *chrome-endpbjjpgkojalfkdmdhmhpgpipbofgd*.desktop

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'locate *chrome-endpbjjpgkojalfkdmdhmhpgpipbofgd*.desktop' } Error: Command failed: locate *chrome-endpbjjpgkojalfkdmdhmhpgpipbofgd*.desktop

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
otherCmd: { '0': 
   { Error: Command failed: locate *chrome-endpbjjpgkojalfkdmdhmhpgpipbofgd*.desktop

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
     killed: false,
     code: 1,
     signal: null,
     cmd: 'locate *chrome-endpbjjpgkojalfkdmdhmhpgpipbofgd*.desktop' } }
(node:12114) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'split' of undefined
(node:12114) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

Here are the contents of my ~/Desktop folder:

```
☁  Desktop  ls -l                               
total 136
-rwxr-xr-x 1 harshp harshp   317 Nov  2 09:19 chrome-abednnnobcbikmhoalpnlijjaloifahb-Default.desktop
-rwxr-xr-x 1 harshp harshp   312 Nov  1 15:57 chrome-bcehchcdiieedggelnphlmeniggngapk-Default.desktop
-rwxr-xr-x 1 harshp harshp   308 Nov 25 06:15 chrome-bpojmmfdjieoohjlafmgnobbmjbkcmoj-Default.desktop
-rwxr-xr-x 1 harshp harshp   318 Nov  1 15:56 chrome-eahagendpjeagehfgdobhplebiikmpfo-Default.desktop
-rwxr-xr-x 1 harshp harshp   308 Nov  1 15:51 chrome-edmijkelpnflahpdblkkobimcplcgmgj-Default.desktop
-rwxr-xr-x 1 harshp harshp   313 Nov  1 15:56 chrome-egdalnmencdpmadgdbcmfiinlfflfbpk-Default.desktop
-rwxr-xr-x 1 harshp harshp   308 Nov 25 06:48 chrome-endpbjjpgkojalfkdmdhmhpgpipbofgd-Default.desktop
-rwxr-xr-x 1 harshp harshp   310 Nov  1 16:09 chrome-eppojlglocelodeimnohnlnionkobfln-Default.desktop
-rwxr-xr-x 1 harshp harshp   312 Nov  1 16:06 chrome-hhhplcgojchhcgcemfpjnmlaceffbgbm-Default.desktop
-rwxr-xr-x 1 harshp harshp   311 Nov 10 11:39 chrome-hnpfjngllnobngcgfapefoaidbinmjnm-Default.desktop
-rwxr-xr-x 1 harshp harshp   313 Nov  2 18:54 chrome-kdnfklpameggkihabegeeiiapiffeeaj-Default.desktop
-rwxr-xr-x 1 harshp harshp   312 Nov  1 16:24 chrome-lepdjejcmiajkejidnijhehjdjklifjd-Default.desktop
-rwxr-xr-x 1 harshp harshp   314 Nov  4 02:49 chrome-miilmjmgkdhdabfkjkilgecbhbchboem-Default.desktop
-rwxr-xr-x 1 harshp harshp   132 Nov  7 21:53 Matlab.desktop
-rwx------ 1 harshp harshp  2191 Jan 14  2017 steam.desktop
```

The chrome-* files are generated using Google Chrome's "More tools -> Add to desktop..." feature. I wonder if that is the problem.

**Comment by harshhpareek** [comment]
Huh, I was able to resolve this issue by running `sudo updatedb`. I looked up the man page for `locate` and it said this command rebuilds the index. I'm still having difficulty using this extension. pressing the save button in the extension does not work, though using lwsm from the command line does. 

It also takes a while to save and restore. I wonder if that's expected.

```
☁  time /home/linuxbrew/.linuxbrew/bin/lwsm save           
SAVED SESSION: DEFAULT
/home/linuxbrew/.linuxbrew/bin/lwsm save  11.96s user 0.06s system 99% cpu 12.037 total
```

**Comment by johannesjo** [comment]
Hey there! Thanks for reporting the issue. Unfortunately executing locate does lead to problems on some systems (see also: https://github.com/johannesjo/linux-window-session-manager/issues/12). Maybe I should replace it with a custom JavaScript handler.

Maybe you can add some global.log statements to the extension to get the output of lwsm. Normally the extension should use the node lib directly, so is weird that there are differences. Maybe you're not on the newest version of the extension?

The delay is unfortunately necessary because the x commands to manipulate the windows start messing up if they're executed simultaneously. I'm not happy with that myself, but afaik there is currently no way around that.

**Comment by johannesjo** [comment]
Hey there. I replaced the `locate`part with a more focused JavaScript handler. This should also improve speed a little. To update run `npm install -g linux-window-session-manager`.

On a further note about the X11: You can play around with the config parameter `GIVE_X11_TIME_TIMEOUT` in `~/.lwsm/config.json` to speed up the restoring of the window positions.

Could you please check if the update solves your problem?
